// wincolors.c
#include <windows.h>
#include <wincon.h>
#include <stdio.h>

const char color2font_color[] = 
{ 0, FOREGROUND_RED | FOREGROUND_INTENSITY, FOREGROUND_GREEN, FOREGROUND_RED, FOREGROUND_BLUE,
  FOREGROUND_BLUE | FOREGROUND_RED, FOREGROUND_GREEN | FOREGROUND_BLUE, 
  FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE, FOREGROUND_RED | FOREGROUND_GREEN,
  FOREGROUND_RED | FOREGROUND_INTENSITY, FOREGROUND_GREEN | FOREGROUND_INTENSITY,
  FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY, FOREGROUND_BLUE | FOREGROUND_INTENSITY,
  FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY,
  FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
  FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
}

const char color2font_bkcolor[] = 
{ 0, BACKGROUND_RED | BACKGROUND_INTENSITY, BACKGROUND_GREEN, BACKGROUND_RED, BACKGROUND_BLUE,
  BACKGROUND_BLUE | BACKGROUND_RED, BACKGROUND_GREEN | BACKGROUND_BLUE, 
  BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE, BACKGROUND_RED | BACKGROUND_GREEN,
  BACKGROUND_RED | BACKGROUND_INTENSITY, BACKGROUND_GREEN | BACKGROUND_INTENSITY,
  BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY, BACKGROUND_BLUE | BACKGROUND_INTENSITY,
  BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY,
  BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
  BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
}


void textcolor(int c){
	WORD wColor; 
	HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
	CONSOLE_SCREEN_BUFFER_INFO csbi;
	
	if(GetConsoleScreenBufferInfo(hStdOut, &csbi)){
		wColor = (csbi.wAttributes & 0xF0) + (c & 0x0F);
		SetConsoleTextAttribute(hStdOut, wColor);     
	}
}

void backcolor(int c){
	WORD wColor; 
	HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
	CONSOLE_SCREEN_BUFFER_INFO csbi;
	
	if(GetConsoleScreenBufferInfo(hStdOut, &csbi)){
		wColor = (csbi.wAttributes & 0x0F) + (c & 0xF0);
		SetConsoleTextAttribute(hStdOut, wColor);     
	}
}

void textattr(int a){
	if( a == CLEAR ){
		//DO SOMETHING
	}
}
